version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"   # Change this to your target region

phases:
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - echo "Logging into Amazon ECR in $AWS_REGION..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 722136401996.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - set -e

      - echo "Building Docker image..."
      - docker build -t example-nodejs .

      - echo "Tagging and pushing Docker image to ECR..."
      - IMAGE_URI="722136401996.dkr.ecr.$AWS_REGION.amazonaws.com/example-nodejs:latest"
      - docker tag example-nodejs:latest $IMAGE_URI
      - docker push $IMAGE_URI

      # ---------- VPC STACK ----------
      - echo "Checking VPC stack..."
      - |
        VPC_STATUS=$(aws cloudformation describe-stacks \
          --region $AWS_REGION \
          --stack-name vpc-stack-$AWS_REGION \
          --query 'Stacks[0].StackStatus' \
          --output text 2>/dev/null || echo "NOT_FOUND")

        if [ "$VPC_STATUS" = "CREATE_IN_PROGRESS" ]; then
          echo "VPC is still creating, exiting build..."
          exit 1
        elif [ "$VPC_STATUS" = "CREATE_COMPLETE" ]; then
          echo "✅ VPC stack already exists, skipping..."
        else
          echo "🚀 Deploying VPC Stack..."
          aws cloudformation deploy \
            --region $AWS_REGION \
            --stack-name vpc-stack-$AWS_REGION \
            --template-file infra/vpc_stack.yml \
            --capabilities CAPABILITY_NAMED_IAM
        fi

      # ---------- ALB STACK ----------
      - echo "Checking ALB stack..."
      - |
        ALB_STATUS=$(aws cloudformation describe-stacks \
          --region $AWS_REGION \
          --stack-name alb-stack-$AWS_REGION \
          --query 'Stacks[0].StackStatus' \
          --output text 2>/dev/null || echo "NOT_FOUND")

        if [ "$ALB_STATUS" = "CREATE_COMPLETE" ]; then
          echo "✅ ALB stack already exists, skipping..."
        else
          echo "🚀 Deploying ALB Stack..."
          aws cloudformation deploy \
            --region $AWS_REGION \
            --stack-name alb-stack-$AWS_REGION \
            --template-file infra/alb_stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides SSLCertificateArn=$CERT_ARN
        fi

      # ---------- ECS STACK ----------
      - echo "Checking ECS stack..."
      - |
        ECS_STATUS=$(aws cloudformation describe-stacks \
          --region $AWS_REGION \
          --stack-name ecs-stack-$AWS_REGION \
          --query 'Stacks[0].StackStatus' \
          --output text 2>/dev/null || echo "NOT_FOUND")

        if [ "$ECS_STATUS" = "CREATE_COMPLETE" ]; then
          echo "✅ ECS stack already exists, skipping..."
        else
          echo "🚀 Deploying ECS Stack..."
          aws cloudformation deploy \
            --region $AWS_REGION \
            --stack-name ecs-stack-$AWS_REGION \
            --template-file infra/ecs_stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              RegionName="$AWS_REGION" \
              KeyName="$KEY_NAME" \
              ECSInstanceRole=$ECS_INSTANCE_ROLE
        fi

      - echo "✅ Deployment completed in $AWS_REGION"

artifacts:
  files:
    - "**/*"
