# Node.js app
FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install --production

# Copy source code
COPY . .

# Expose port Node.js listens on
EXPOSE 8080

# Start the Node.js server
CMD ["node", "app.js"]
