# ALB Template
---
AWSTemplateFormatVersion: "2010-09-09"
Description: ALB stack including Security Group, ALB, Target Groups, and Listeners

Parameters:
  SSLCertificateArn:
    Type: String

Resources:
  CMS3ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows HTTP/HTTPS traffic"
      VpcId: !ImportValue CMS3VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: CMS3-ALB-SG

  CMSNodejsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue CMS3VPC
      Protocol: HTTP
      Port: 8080                    # Container port
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: CMS3-NodeJS-TG

  CMS3ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: CMS3ApplicationLoadBalancer
      SecurityGroups:
        - !Ref CMS3ALBSecurityGroup
      Subnets:
        - !ImportValue CMS3PublicSubnet1
        - !ImportValue CMS3PublicSubnet2
      Scheme: internet-facing
      Type: application

  CMS3ALBHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CMS3ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CMSNodejsTargetGroup

  CMS3ALBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CMS3ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

Outputs:
  CMSNodejsTargetGroupARN:
    Description: Node.js Target Group ARN
    Value: !Ref CMSNodejsTargetGroup
    Export:
      Name: CMSNodejsTargetGroup

  ALBSecurityGroupId:
    Description: Security Group ID for ALB
    Value: !Ref CMS3ALBSecurityGroup
    Export:
      Name: CMS3ALBSecurityGroup

  ALBArn:
    Description: ALB ARN
    Value: !Ref CMS3ApplicationLoadBalancer
    Export:
      Name: CMS3ApplicationLoadBalancer

  CMS3ALBDNSName:
    Description: DNS Name of the Application Load Balancer
    Value: !GetAtt CMS3ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub CMS3-ALB-DNS-${AWS::Region}
