AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster on EC2 with ALB Integration (Instance Target Type)

Parameters:
  RegionName:
    Type: String
    Description: Region name used in ECR image
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  ECSAMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  ECSInstanceRole:
    Type: String
  ECSTaskExecutionRoleArn:
    Type: String
    Description: Existing ECS Task Execution Role ARN   # ✅ added

Resources:

  CMS3TestEC2Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CMS3TestEC2Cluster

  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB and SSH
      VpcId: !ImportValue CMS3VPC
      SecurityGroupIngress:
        # ✅ Allow all ports from ALB SG (because bridge mode can vary host port mapping)
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !ImportValue CMS3ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSInstanceRole

  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.xlarge
        ImageId: !Ref ECSAMI
        IamInstanceProfile:
          Name: !Ref ECSInstanceProfile
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref EC2InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=CMS3TestEC2Cluster >> /etc/ecs/ecs.config

  CMS3ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: ECSLaunchTemplate
    Properties:
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "1"
      VPCZoneIdentifier:
        - !ImportValue CMS3PrivateSubnet1
        - !ImportValue CMS3PrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber

  # ✅ Attach ASG to ECS cluster using Capacity Provider
  ECSCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref CMS3ECSAutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 80

  ECSClusterCPAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref CMS3TestEC2Cluster
      CapacityProviders:
        - !Ref ECSCapacityProvider
      DefaultCapacityProviderStrategy:
        - CapacityProvider: !Ref ECSCapacityProvider
          Weight: 1

  NodejsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nodejs-service-td
      RequiresCompatibilities: [EC2]
      NetworkMode: bridge
      Cpu: 1024
      Memory: 3072
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: nodejs
          Image: !Sub 722136401996.dkr.ecr.${RegionName}.amazonaws.com/example-nodejs:latest
          Essential: true
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: "/ecs/cms3-ecs-ec2-loggroup"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"

  NodejsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref CMS3TestEC2Cluster
      ServiceName: NodejsService
      LaunchType: EC2
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60   # ✅ Give time for container to boot
      LoadBalancers:
        - ContainerName: nodejs
          ContainerPort: 8080
          TargetGroupArn: !ImportValue CMSNodejsTargetGroup
      TaskDefinition: !Ref NodejsTaskDefinition
